import { type Category, type Product } from '@/types';

// ---- Categories ----
export const CATEGORIES: Category[] = [
  { id: '1', name: 'Creator Gear', icon: '🎬', slug: 'creator-gear', description: 'Cameras, lighting, microphones' },
  { id: '2', name: 'Cameras', icon: '📷', slug: 'cameras', description: 'DSLRs, mirrorless, action cams' },
  { id: '3', name: 'Drones', icon: '🚁', slug: 'drones', description: 'FPV drones, aerial photography' },
  { id: '4', name: 'Bikes', icon: '🚲', slug: 'bikes', description: 'Bicycles, e-bikes, scooters' },
  { id: '5', name: 'Electronics', icon: '💻', slug: 'electronics', description: 'Laptops, tablets, gadgets' },
  { id: '6', name: 'Tools', icon: '🔧', slug: 'tools', description: 'Power tools, hand tools' },
  { id: '7', name: 'Event Equipment', icon: '🎤', slug: 'event-equipment', description: 'Sound, lighting, stages' },
  { id: '8', name: 'Machinery', icon: '⚙️', slug: 'machinery', description: 'Industrial equipment' },
  { id: '9', name: 'Food Carts', icon: '🍕', slug: 'food-carts', description: 'Mobile food stations' },
  { id: '10', name: 'Student Essentials', icon: '📚', slug: 'student-essentials', description: 'Study tools, instruments' },
];

// ---- Mock Products ----
export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    owner_id: 'owner1',
    category_id: '2',
    title: 'Sony Alpha A7S III Creator Kit',
    description: 'Professional full-frame mirrorless camera perfect for videography, low-light shooting, and content creation. Includes 24-70mm f/2.8 lens, extra batteries, and memory cards.',
    price_per_day: 2500,
    deposit_amount: 10000,
    city: 'Coimbatore',
    area: 'RS Puram',
    lat: 11.0168,
    lng: 76.9558,
    status: 'active',
    rating: 4.9,
    review_count: 47,
    is_featured: true,
    created_at: '2024-01-15',
    images: [
      { id: 'i1', product_id: '1', image_url: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80', order: 0 },
      { id: 'i2', product_id: '1', image_url: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&q=80', order: 1 },
      { id: 'i3', product_id: '1', image_url: 'https://images.unsplash.com/photo-1581591524425-c7e0978865fc?w=800&q=80', order: 2 },
    ],
    category: CATEGORIES[1],
    owner: { full_name: 'Karthik Studios', avatar_url: 'https://i.pravatar.cc/100?img=12' },
  },
  {
    id: '2',
    owner_id: 'owner2',
    category_id: '3',
    title: 'DJI Mavic 3 Pro Drone',
    description: 'Professional-grade drone with 4/3 CMOS Hasselblad camera, 46-min flight time, and omnidirectional obstacle sensing. Perfect for aerial photography and videography.',
    price_per_day: 3500,
    deposit_amount: 15000,
    city: 'Coimbatore',
    area: 'Saibaba Colony',
    lat: 11.0245,
    lng: 76.9628,
    status: 'active',
    rating: 4.8,
    review_count: 32,
    is_featured: true,
    created_at: '2024-01-20',
    images: [
      { id: 'i4', product_id: '2', image_url: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800&q=80', order: 0 },
      { id: 'i5', product_id: '2', image_url: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=800&q=80', order: 1 },
    ],
    category: CATEGORIES[2],
    owner: { full_name: 'AerialShot CBE', avatar_url: 'https://i.pravatar.cc/100?img=22' },
  },
  {
    id: '3',
    owner_id: 'owner3',
    category_id: '4',
    title: 'Trek FX3 Hybrid City Bike',
    description: 'Lightweight aluminum frame hybrid bike, perfect for city commutes and weekend rides. Smooth 24-speed Shimano gears. Helmet and lock included.',
    price_per_day: 399,
    deposit_amount: 2000,
    city: 'Coimbatore',
    area: 'Peelamedu',
    lat: 11.0189,
    lng: 77.0283,
    status: 'active',
    rating: 4.7,
    review_count: 89,
    is_featured: true,
    created_at: '2024-02-01',
    images: [
      { id: 'i6', product_id: '3', image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80', order: 0 },
    ],
    category: CATEGORIES[3],
    owner: { full_name: 'Ride CBE', avatar_url: 'https://i.pravatar.cc/100?img=33' },
  },
  {
    id: '4',
    owner_id: 'owner4',
    category_id: '7',
    title: 'Mobile Food Cart — Full Setup',
    description: 'Complete commercial food cart with built-in gas burner, storage compartments, LED lighting, and umbrella. Ideal for events, weddings, and business launches.',
    price_per_day: 1500,
    deposit_amount: 5000,
    city: 'Coimbatore',
    area: 'Gandhipuram',
    lat: 11.0059,
    lng: 76.9673,
    status: 'active',
    rating: 4.6,
    review_count: 18,
    is_featured: false,
    created_at: '2024-02-10',
    images: [
      { id: 'i7', product_id: '4', image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80', order: 0 },
    ],
    category: CATEGORIES[8],
    owner: { full_name: 'Event Supplies CBE', avatar_url: 'https://i.pravatar.cc/100?img=44' },
  },
  {
    id: '5',
    owner_id: 'owner5',
    category_id: '6',
    title: 'DeWalt 20V MAX Power Tool Set',
    description: '12-piece cordless power tool kit including drill, impact driver, circular saw, jigsaw, and more. Fast charger and 4Ah batteries included.',
    price_per_day: 799,
    deposit_amount: 3000,
    city: 'Coimbatore',
    area: 'Singanallur',
    lat: 11.0002,
    lng: 77.0261,
    status: 'active',
    rating: 4.8,
    review_count: 56,
    is_featured: true,
    created_at: '2024-02-15',
    images: [
      { id: 'i8', product_id: '5', image_url: 'https://images.unsplash.com/photo-1581244277943-fe4a9c777189?w=800&q=80', order: 0 },
    ],
    category: CATEGORIES[5],
    owner: { full_name: 'ToolRent CBE', avatar_url: 'https://i.pravatar.cc/100?img=55' },
  },
  {
    id: '6',
    owner_id: 'owner1',
    category_id: '1',
    title: 'Studio Lighting Kit — 3 Softbox',
    description: 'Professional 3-point studio lighting setup with 85W LED bulbs, softboxes, stands, and diffusers. Perfect for portrait, product, and video shoots.',
    price_per_day: 899,
    deposit_amount: 3500,
    city: 'Coimbatore',
    area: 'RS Puram',
    lat: 11.0168,
    lng: 76.9558,
    status: 'active',
    rating: 4.9,
    review_count: 34,
    is_featured: false,
    created_at: '2024-03-01',
    images: [
      { id: 'i9', product_id: '6', image_url: 'https://images.unsplash.com/photo-1518791841217-8f162f1912da?w=800&q=80', order: 0 },
    ],
    category: CATEGORIES[0],
    owner: { full_name: 'Karthik Studios', avatar_url: 'https://i.pravatar.cc/100?img=12' },
  },
  {
    id: '7',
    owner_id: 'owner6',
    category_id: '5',
    title: 'MacBook Pro 16" M3 Pro',
    description: 'Apple MacBook Pro 16" with M3 Pro chip, 18GB RAM, 512GB SSD. Pre-installed with Final Cut Pro, Adobe Creative Suite, and MS Office. Ideal for creative professionals.',
    price_per_day: 1299,
    deposit_amount: 8000,
    city: 'Coimbatore',
    area: 'Tidel Park',
    lat: 11.0074,
    lng: 76.9974,
    status: 'active',
    rating: 5.0,
    review_count: 22,
    is_featured: true,
    created_at: '2024-03-05',
    images: [
      { id: 'i10', product_id: '7', image_url: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80', order: 0 },
    ],
    category: CATEGORIES[4],
    owner: { full_name: 'TechRent CBE', avatar_url: 'https://i.pravatar.cc/100?img=66' },
  },
  {
    id: '8',
    owner_id: 'owner4',
    category_id: '7',
    title: 'PA Sound System — 10,000W',
    description: 'Complete professional PA sound system with 2x 18" subwoofers, 4x line array tops, 2x amplifiers, mixer, cables, and mic set. Ideal for events up to 1000 people.',
    price_per_day: 4999,
    deposit_amount: 20000,
    city: 'Coimbatore',
    area: 'Gandhipuram',
    lat: 11.0059,
    lng: 76.9673,
    status: 'active',
    rating: 4.7,
    review_count: 41,
    is_featured: false,
    created_at: '2024-03-10',
    images: [
      { id: 'i11', product_id: '8', image_url: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800&q=80', order: 0 },
    ],
    category: CATEGORIES[6],
    owner: { full_name: 'Event Supplies CBE', avatar_url: 'https://i.pravatar.cc/100?img=44' },
  },
];

export const TESTIMONIALS = [
  {
    id: '1',
    name: 'Priya Ramachandran',
    role: 'Content Creator',
    city: 'Coimbatore',
    avatar: 'https://i.pravatar.cc/100?img=5',
    rating: 5,
    text: 'Rented a Sony A7S III for my wedding shoot. The camera was in perfect condition and the owner was super helpful. Saved ₹2 lakhs compared to buying!',
  },
  {
    id: '2',
    name: 'Arun Selvam',
    role: 'Freelance Photographer',
    city: 'Tiruppur',
    avatar: 'https://i.pravatar.cc/100?img=15',
    rating: 5,
    text: 'Listed my extra camera on Rento and made ₹15,000 in just 2 months. The platform handles everything — payments, bookings, and verification. Highly recommend!',
  },
  {
    id: '3',
    name: 'Meena Krishnamurthy',
    role: 'Event Organizer',
    city: 'Coimbatore',
    avatar: 'https://i.pravatar.cc/100?img=25',
    rating: 5,
    text: 'Rented the PA sound system for our company event. Delivery was on time, setup was easy, and the quality was excellent. Will definitely use Rento again!',
  },
];

export const HOW_IT_WORKS = [
  {
    step: 1,
    title: 'Find',
    description: 'Browse thousands of local listings near you. Filter by category, price, and availability.',
    icon: '🔍',
  },
  {
    step: 2,
    title: 'Book',
    description: 'Select your rental dates and confirm with our secure payment gateway.',
    icon: '📅',
  },
  {
    step: 3,
    title: 'Use',
    description: 'Meet the owner or get it delivered. Enjoy your rental with full insurance coverage.',
    icon: '🎯',
  },
  {
    step: 4,
    title: 'Return',
    description: 'Return the product and get your deposit back. Leave a review for the owner.',
    icon: '↩️',
  },
];

export const TRUST_FEATURES = [
  {
    icon: '✅',
    title: 'Verified Owners',
    description: 'Every owner is Aadhaar and PAN verified before listing products.',
  },
  {
    icon: '🔒',
    title: 'Secure Payments',
    description: 'All payments are processed through Razorpay — 100% safe and encrypted.',
  },
  {
    icon: '🛡️',
    title: 'Damage Protection',
    description: 'Mandatory deposits protect owners. Dispute resolution within 48 hours.',
  },
  {
    icon: '🎧',
    title: '24/7 Support',
    description: 'Our team is always here to help you throughout your rental experience.',
  },
];

export const INDIAN_CITIES = [
  'Coimbatore', 'Chennai', 'Bangalore', 'Hyderabad', 'Mumbai',
  'Delhi', 'Pune', 'Kolkata', 'Ahmedabad', 'Jaipur',
  'Tiruppur', 'Erode', 'Salem', 'Madurai', 'Trichy',
];
